### ISSUE TITLE
unity安装环境不一样导致DyncDll.csproj无法正常识别依赖库

### ISSUE THREAD

**Issue by huangchaoqun** [wuxiongbin/XIL#6]
现在是没有把热更工程加入版控 每个人通过执行下UnityAutoProject.exe再打工热更工程 有什么好的解决方案吗？把DyncDll.csproj的依赖库全部单独拷贝到工程路径？

**Comment by wuxiongbin** [comment]
u3d版本不升级的情况下，可以这么做，基本没啥影响。
理论上来说，热更工程依赖的DLL是固定的，有调整，再手动添加也可以
